# Generated by Django 5.1.1 on 2024-10-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                default="default@example.com", max_length=254, unique=True
            ),
        ),
    ]
