# Generated by Django 5.1.1 on 2024-10-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password_hash",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
